import os
import json

# 定义表头和介绍文案
header = """# LeetCode 75 - Jupyter Notebook Edition 📓

This repository contains my solutions for the LeetCode 75 study plan. 
I use a **"Solve-then-Review"** methodology using Jupyter Notebooks.

## 🧠 Study Methodology: Spaced Repetition

- **Day 1 (Implementation)**: Focus on solving the problem and passing test cases.
- **Day 2 (Retrospection)**: Revisit the solution after 24 hours to write **Takeaways**, analyze complexity, and optimize code.

---

## 📊 Progress Tracker

| Category | Problem | 💻 Day 1: Code | 📝 Day 2: Takeaways |
| :--- | :--- | :---: | :---: |
"""

footer = """
---
*Auto-generated by script. Happy Coding!*
"""

def analyze_notebook(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
            
        cells = data.get("cells", [])
        
        # 1. 检测代码 (Day 1)
        # 假设代码在第2个Cell (Index 1)
        code_status = "⬜"
        if len(cells) > 1 and cells[1]['cell_type'] == 'code':
            source = "".join(cells[1]['source']).strip()
            # 如果代码长度大于 50 且不包含 "pass" (且不仅是空的)，认为已写
            if len(source) > 50 and "pass" not in source:
                code_status = "✅"

        # 2. 检测笔记 (Day 2)
        # 假设笔记在第3个Cell (Index 2)
        note_status = "⬜"
        if len(cells) > 2 and cells[2]['cell_type'] == 'markdown':
            source = "".join(cells[2]['source'])
            # 检测是否勾选了 [x] 或者笔记字数显著增加
            if "[x]" in source:
                note_status = "✅"
            elif code_status == "✅":
                # 如果写了代码但没勾选笔记，显示等待中
                note_status = "⏳"
        
        return code_status, note_status
    except Exception as e:
        return "⚠️", "⚠️"

# 主逻辑
content = header
total_solved = 0
total_reviewed = 0

# 按文件名排序，保证顺序一致
for root, dirs, files in os.walk("."):
    dirs.sort() # 确保 01, 02... 顺序
    if ".git" in root or ".ipynb_checkpoints" in root:
        continue
        
    category = os.path.basename(root)
    # 只要 01-22 开头的文件夹
    if not category[0].isdigit():
        continue
        
    # 处理该分类下的文件
    files.sort()
    # 这一行是为了只显示分类名称一次，做个标记
    first_in_category = True
    
    clean_category_name = category.replace("_", " ")
    
    for file in files:
        if file.endswith(".ipynb"):
            filepath = os.path.join(root, file)
            
            # 解析题目名 (去掉 ID 和 后缀)
            # 1768_Merge_Strings.ipynb -> Merge Strings
            try:
                raw_name = file.replace(".ipynb", "")
                parts = raw_name.split("_")
                if parts[0].isdigit():
                    display_name = " ".join(parts[1:])
                    problem_id = parts[0]
                    full_display = f"**{problem_id}.** {display_name}"
                else:
                    full_display = raw_name
            except:
                full_display = file

            # 分析状态
            c_stat, n_stat = analyze_notebook(filepath)
            
            if c_stat == "✅": total_solved += 1
            if n_stat == "✅": total_reviewed += 1
            
            # 只有当分类第一次出现时显示名字，后面留空，保持表格整洁
            cat_col = f"**{clean_category_name}**" if first_in_category else ""
            
            # 生成连到 Notebook 的链接
            link = f"[{full_display}](./{category}/{file})"
            
            content += f"| {cat_col} | {link} | {c_stat} | {n_stat} |\n"
            first_in_category = False

# 写入 README
with open("README.md", "w", encoding="utf-8") as f:
    f.write(content + footer)

print(f"✅ README updated! Solved: {total_solved}, Reviewed: {total_reviewed}")
